// Display names and categories for every PathogenId (used by the pipeline and the app).
import type { PathogenCategory, PathogenId } from './types.ts'

export const PATHOGEN_INFO: Record<PathogenId, { name: string; short: string; category: PathogenCategory }> = {
  influenza: { name: 'Influenza (flu)', short: 'Flu', category: 'respiratory-viral' },
  'influenza-a': { name: 'Influenza A', short: 'Flu A', category: 'respiratory-viral' },
  'influenza-b': { name: 'Influenza B', short: 'Flu B', category: 'respiratory-viral' },
  rsv: { name: 'Respiratory syncytial virus (RSV)', short: 'RSV', category: 'respiratory-viral' },
  covid: { name: 'COVID-19', short: 'COVID-19', category: 'respiratory-viral' },
  hmpv: { name: 'Human metapneumovirus (hMPV)', short: 'hMPV', category: 'respiratory-viral' },
  'rhino-entero': { name: 'Rhinovirus / enterovirus', short: 'Rhino/enterovirus', category: 'respiratory-viral' },
  adenovirus: { name: 'Adenovirus (respiratory)', short: 'Adenovirus', category: 'respiratory-viral' },
  parainfluenza: { name: 'Parainfluenza', short: 'Parainfluenza', category: 'respiratory-viral' },
  'seasonal-cov': { name: 'Seasonal coronaviruses', short: 'Seasonal coronaviruses', category: 'respiratory-viral' },
  mycoplasma: { name: 'Mycoplasma pneumoniae (walking pneumonia)', short: 'Mycoplasma', category: 'respiratory-bacterial' },
  pertussis: { name: 'Pertussis (whooping cough)', short: 'Whooping cough', category: 'respiratory-bacterial' },
  'chlamydia-pneumoniae': { name: 'Chlamydia pneumoniae', short: 'C. pneumoniae', category: 'respiratory-bacterial' },
  'strep-a': { name: 'Group A strep', short: 'Strep A', category: 'respiratory-bacterial' },
  norovirus: { name: 'Norovirus', short: 'Norovirus', category: 'gastrointestinal' },
  rotavirus: { name: 'Rotavirus', short: 'Rotavirus', category: 'gastrointestinal' },
  sapovirus: { name: 'Sapovirus', short: 'Sapovirus', category: 'gastrointestinal' },
  astrovirus: { name: 'Astrovirus', short: 'Astrovirus', category: 'gastrointestinal' },
  'adenovirus-gi': { name: 'Adenovirus 40/41 (stomach)', short: 'Adenovirus 40/41', category: 'gastrointestinal' },
  salmonella: { name: 'Salmonella', short: 'Salmonella', category: 'gastrointestinal' },
  campylobacter: { name: 'Campylobacter', short: 'Campylobacter', category: 'gastrointestinal' },
  stec: { name: 'Shiga toxin–producing E. coli (STEC)', short: 'E. coli (STEC)', category: 'gastrointestinal' },
  shigella: { name: 'Shigella', short: 'Shigella', category: 'gastrointestinal' },
  'c-diff': { name: 'C. difficile', short: 'C. diff', category: 'gastrointestinal' },
  cyclospora: { name: 'Cyclospora', short: 'Cyclospora', category: 'gastrointestinal' },
  giardia: { name: 'Giardia', short: 'Giardia', category: 'gastrointestinal' },
  cryptosporidium: { name: 'Cryptosporidium', short: 'Crypto', category: 'gastrointestinal' },
  measles: { name: 'Measles', short: 'Measles', category: 'vaccine-preventable' },
  'hepatitis-a': { name: 'Hepatitis A', short: 'Hepatitis A', category: 'vaccine-preventable' },
  mpox: { name: 'Mpox', short: 'Mpox', category: 'vaccine-preventable' },
  lyme: { name: 'Lyme disease', short: 'Lyme', category: 'vector-borne' },
  anaplasmosis: { name: 'Anaplasmosis', short: 'Anaplasmosis', category: 'vector-borne' },
  babesiosis: { name: 'Babesiosis', short: 'Babesiosis', category: 'vector-borne' },
  'west-nile': { name: 'West Nile virus', short: 'West Nile', category: 'vector-borne' },
  h5n1: { name: 'H5N1 bird flu', short: 'H5 bird flu', category: 'zoonotic' },
  'respiratory-combined': { name: 'Respiratory illness (all causes)', short: 'Respiratory illness', category: 'syndrome' },
  ili: { name: 'Influenza-like illness', short: 'Flu-like illness', category: 'syndrome' },
}

export const pathogenShort = (id: PathogenId) => PATHOGEN_INFO[id]?.short ?? id
