import {
  Color,
  DataTexture,
  LinearMipmapLinearFilter,
  LinearFilter,
  RepeatWrapping,
  RGBAFormat,
  SRGBColorSpace,
  UnsignedByteType,
} from 'three';
import type { SubstrateKind } from '../../core/types';
import { Rng } from '../../core/rng';

/**
 * Procedural, tileable substrate detail textures (albedo+height, normal, occlusion/roughness),
 * generated by "pouring" thousands of grains into a periodic height buffer: each grain is an
 * irregular ellipse with its own color, roughness and height profile, z-buffered against the
 * grains already there so they pack and overlap like real sediment. Grain sizes and colors are
 * taken from real aquarium substrates (sizes in mm; colors are wet, sRGB).
 */

type RGB = [number, number, number];

interface Swatch {
  c: RGB;
  /** Relative frequency. */
  w: number;
  /** Roughness override (wet polished pebbles ≈ 0.35, matte soil ≈ 0.9). */
  rough?: number;
}

interface GrainLayer {
  /** Area coverage multiplier (≥1.5 gives a fully packed layer). */
  coverage: number;
  /** Grain radius range (mm). */
  rMin: number;
  rMax: number;
  /** Elongation range (1 = round). */
  aspect: [number, number];
  /** Outline irregularity 0 (smooth ellipse) .. 0.35 (angular, fractured). */
  rough: number;
  /** 'dome' rounded grains, 'facet' angular fragments, 'flake' flat shell bits. */
  profile: 'dome' | 'facet' | 'flake';
  /** Relative dome height (fraction of radius). */
  height: number;
  /** Within-grain albedo noise amplitude. */
  speckle: number;
  /** Per-grain color jitter (fraction). */
  jitter: number;
  palette: Swatch[];
  /** Default roughness for this layer. */
  roughness: number;
}

export interface SubstrateSpec {
  /** Meters covered by one texture tile. */
  tile: number;
  /** Color of the voids between grains (sRGB). */
  voidColor: RGB;
  layers: GrainLayer[];
  /** Large-scale tone variation in the shader: amplitude and tint direction. */
  macroAmp: number;
  macroTint: RGB;
  /** Normal map strength. */
  normalScale: number;
  /** Gentle mid-scale undulation of the surface (fraction of tile). */
  undulation: number;
}

// ---------------------------------------------------------------------------------------------
// Specs per substrate kind
// ---------------------------------------------------------------------------------------------

const sand = (palette: Swatch[], rMin: number, rMax: number, extra: Partial<GrainLayer> = {}): GrainLayer => ({
  coverage: 2.4, rMin, rMax, aspect: [1, 1.5], rough: 0.12, profile: 'dome', height: 0.7, speckle: 0.06, jitter: 0.07,
  palette, roughness: 0.62, ...extra,
});

export const SUBSTRATE_SPECS: Record<Exclude<SubstrateKind, 'bare'>, SubstrateSpec> = {
  'white-sand': {
    tile: 0.06, voidColor: [0.5, 0.49, 0.46], macroAmp: 0.06, macroTint: [1.0, 0.97, 0.9], normalScale: 0.9, undulation: 0.012,
    layers: [sand([
      { c: [0.9, 0.89, 0.85], w: 6 }, { c: [0.84, 0.83, 0.79], w: 4 }, { c: [0.95, 0.94, 0.91], w: 3 },
      { c: [0.74, 0.72, 0.68], w: 1.2 }, { c: [0.6, 0.58, 0.55], w: 0.3 }, { c: [0.3, 0.29, 0.28], w: 0.08 },
      { c: [0.86, 0.8, 0.7], w: 0.6 },
    ], 0.16, 0.32)],
  },
  'beige-sand': {
    tile: 0.06, voidColor: [0.42, 0.36, 0.27], macroAmp: 0.08, macroTint: [1.0, 0.92, 0.78], normalScale: 0.9, undulation: 0.012,
    layers: [sand([
      { c: [0.83, 0.73, 0.57], w: 5 }, { c: [0.76, 0.64, 0.48], w: 4 }, { c: [0.9, 0.83, 0.7], w: 2.5 },
      { c: [0.64, 0.53, 0.4], w: 1.6 }, { c: [0.93, 0.9, 0.84], w: 0.7 }, { c: [0.4, 0.34, 0.28], w: 0.3 },
      { c: [0.7, 0.5, 0.36], w: 0.5 },
    ], 0.17, 0.34)],
  },
  'black-sand': {
    tile: 0.06, voidColor: [0.025, 0.025, 0.028], macroAmp: 0.05, macroTint: [0.9, 0.95, 1.0], normalScale: 1.0, undulation: 0.012,
    layers: [sand([
      { c: [0.09, 0.09, 0.095], w: 5 }, { c: [0.14, 0.14, 0.145], w: 3.5 }, { c: [0.055, 0.055, 0.06], w: 3 },
      { c: [0.22, 0.21, 0.2], w: 0.8 }, { c: [0.55, 0.55, 0.53], w: 0.12, rough: 0.2 }, { c: [0.28, 0.24, 0.2], w: 0.3 },
    ], 0.18, 0.36, { roughness: 0.45 })],
  },
  'river-sand': {
    tile: 0.1, voidColor: [0.3, 0.26, 0.21], macroAmp: 0.1, macroTint: [1.0, 0.9, 0.78], normalScale: 1.1, undulation: 0.01,
    layers: [
      sand([{ c: [0.6, 0.53, 0.43], w: 3 }, { c: [0.45, 0.39, 0.31], w: 2 }], 0.12, 0.22, { coverage: 1.4 }),
      sand([
        { c: [0.78, 0.68, 0.52], w: 4 }, { c: [0.56, 0.43, 0.31], w: 2.5 }, { c: [0.62, 0.61, 0.58], w: 2.2 },
        { c: [0.9, 0.88, 0.83], w: 1.6 }, { c: [0.27, 0.24, 0.21], w: 1.2 }, { c: [0.68, 0.45, 0.3], w: 1.1 },
        { c: [0.83, 0.77, 0.64], w: 2 },
      ], 0.25, 0.8, { coverage: 2.0, rough: 0.16, height: 0.65, roughness: 0.55 }),
    ],
  },
  'fine-gravel': {
    tile: 0.12, voidColor: [0.16, 0.14, 0.12], macroAmp: 0.09, macroTint: [1.0, 0.9, 0.8], normalScale: 1.3, undulation: 0.008,
    layers: [
      sand([{ c: [0.42, 0.37, 0.3], w: 1 }], 0.15, 0.3, { coverage: 1.2 }),
      {
        coverage: 2.1, rMin: 0.7, rMax: 1.7, aspect: [1, 1.6], rough: 0.14, profile: 'dome', height: 0.75, speckle: 0.08, jitter: 0.08,
        roughness: 0.42,
        palette: [
          { c: [0.74, 0.62, 0.46], w: 3 }, { c: [0.85, 0.8, 0.7], w: 2 }, { c: [0.52, 0.4, 0.29], w: 2 },
          { c: [0.6, 0.59, 0.56], w: 2 }, { c: [0.32, 0.3, 0.28], w: 1.4 }, { c: [0.7, 0.47, 0.32], w: 1.2 },
        ],
      },
    ],
  },
  'pea-gravel': {
    tile: 0.22, voidColor: [0.09, 0.08, 0.07], macroAmp: 0.08, macroTint: [1.0, 0.92, 0.82], normalScale: 1.5, undulation: 0.006,
    layers: [
      sand([{ c: [0.4, 0.35, 0.29], w: 1 }], 0.3, 0.7, { coverage: 1.2 }),
      {
        coverage: 1.9, rMin: 2.2, rMax: 4.6, aspect: [1.05, 1.55], rough: 0.1, profile: 'dome', height: 0.8, speckle: 0.07, jitter: 0.06,
        roughness: 0.36,
        palette: [
          { c: [0.76, 0.61, 0.43], w: 3 }, { c: [0.87, 0.81, 0.7], w: 2.2 }, { c: [0.55, 0.4, 0.28], w: 2 },
          { c: [0.63, 0.61, 0.58], w: 2 }, { c: [0.72, 0.46, 0.31], w: 1.4 }, { c: [0.36, 0.33, 0.31], w: 1.2 },
          { c: [0.82, 0.7, 0.5], w: 1.5 },
        ],
      },
    ],
  },
  'aqua-soil': {
    tile: 0.14, voidColor: [0.035, 0.028, 0.022], macroAmp: 0.07, macroTint: [1.0, 0.9, 0.8], normalScale: 1.4, undulation: 0.008,
    layers: [{
      coverage: 2.3, rMin: 0.9, rMax: 2.0, aspect: [1, 1.35], rough: 0.2, profile: 'dome', height: 0.65, speckle: 0.12, jitter: 0.1,
      roughness: 0.9,
      palette: [
        { c: [0.17, 0.13, 0.1], w: 4 }, { c: [0.22, 0.17, 0.13], w: 3 }, { c: [0.12, 0.1, 0.08], w: 3 },
        { c: [0.28, 0.22, 0.16], w: 1.3 }, { c: [0.2, 0.18, 0.15], w: 1 },
      ],
    }],
  },
  'black-gravel': {
    tile: 0.16, voidColor: [0.02, 0.02, 0.022], macroAmp: 0.05, macroTint: [0.92, 0.95, 1.0], normalScale: 1.5, undulation: 0.006,
    layers: [
      sand([{ c: [0.06, 0.06, 0.065], w: 1 }], 0.25, 0.5, { coverage: 1.2 }),
      {
        coverage: 2.0, rMin: 1.2, rMax: 2.6, aspect: [1.1, 1.8], rough: 0.3, profile: 'facet', height: 0.6, speckle: 0.1, jitter: 0.12,
        roughness: 0.32,
        palette: [
          { c: [0.08, 0.08, 0.085], w: 4 }, { c: [0.13, 0.13, 0.14], w: 3 }, { c: [0.19, 0.19, 0.2], w: 1.5 },
          { c: [0.05, 0.05, 0.055], w: 2 },
        ],
      },
    ],
  },
  'crushed-coral': {
    tile: 0.2, voidColor: [0.48, 0.45, 0.4], macroAmp: 0.07, macroTint: [1.0, 0.94, 0.88], normalScale: 1.4, undulation: 0.006,
    layers: [
      sand([{ c: [0.86, 0.83, 0.76], w: 3 }, { c: [0.78, 0.74, 0.66], w: 2 }], 0.25, 0.6, { coverage: 1.5 }),
      {
        coverage: 1.7, rMin: 1.2, rMax: 3.8, aspect: [1.1, 2.0], rough: 0.32, profile: 'facet', height: 0.55, speckle: 0.09, jitter: 0.07,
        roughness: 0.7,
        palette: [
          { c: [0.93, 0.91, 0.87], w: 4 }, { c: [0.88, 0.82, 0.72], w: 2.5 }, { c: [0.88, 0.76, 0.72], w: 1.2 },
          { c: [0.82, 0.74, 0.62], w: 1.5 }, { c: [0.72, 0.62, 0.68], w: 0.5 }, { c: [0.96, 0.95, 0.92], w: 1.5 },
        ],
      },
      {
        coverage: 0.25, rMin: 1.5, rMax: 3.2, aspect: [1.6, 2.8], rough: 0.08, profile: 'flake', height: 0.25, speckle: 0.05, jitter: 0.06,
        roughness: 0.4,
        palette: [{ c: [0.95, 0.9, 0.84], w: 2 }, { c: [0.85, 0.66, 0.55], w: 1 }, { c: [0.9, 0.84, 0.76], w: 1.5 }],
      },
    ],
  },
  aragonite: {
    tile: 0.085, voidColor: [0.55, 0.52, 0.47], macroAmp: 0.06, macroTint: [1.0, 0.96, 0.9], normalScale: 1.0, undulation: 0.01,
    layers: [
      sand([
        { c: [0.93, 0.9, 0.84], w: 5 }, { c: [0.88, 0.84, 0.76], w: 3 }, { c: [0.96, 0.95, 0.91], w: 3 },
        { c: [0.86, 0.78, 0.72], w: 0.8 }, { c: [0.78, 0.72, 0.62], w: 1 },
      ], 0.25, 0.85, { coverage: 2.3, roughness: 0.66 }),
      {
        coverage: 0.18, rMin: 0.8, rMax: 1.8, aspect: [1.5, 2.6], rough: 0.06, profile: 'flake', height: 0.25, speckle: 0.05, jitter: 0.05,
        roughness: 0.45,
        palette: [{ c: [0.96, 0.93, 0.88], w: 2 }, { c: [0.86, 0.7, 0.6], w: 1 }],
      },
    ],
  },
};

// ---------------------------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------------------------

export interface SubstrateTextures {
  /** RGB = albedo (sRGB), A = height (0..1) used for height-blended anti-tiling. */
  albedo: DataTexture;
  /** Tangent-space normal map. */
  normal: DataTexture;
  /** R = ambient occlusion, G = roughness. */
  orm: DataTexture;
  /** Mean albedo, linear. */
  meanAlbedo: Color;
  spec: SubstrateSpec;
}

const cache = new Map<string, SubstrateTextures>();

function srgbToLinear(c: number): number {
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

/** Separable periodic box blur (in place via scratch). */
function boxBlurWrap(src: Float32Array, size: number, radius: number, scratch: Float32Array): void {
  const r = Math.max(1, Math.round(radius));
  const norm = 1 / (2 * r + 1);
  for (let pass = 0; pass < 2; pass++) {
    const from = pass === 0 ? src : scratch;
    const to = pass === 0 ? scratch : src;
    for (let line = 0; line < size; line++) {
      let acc = 0;
      for (let k = -r; k <= r; k++) {
        const i = (k + size) % size;
        acc += pass === 0 ? from[line * size + i] : from[i * size + line];
      }
      for (let i = 0; i < size; i++) {
        if (pass === 0) to[line * size + i] = acc * norm;
        else to[i * size + line] = acc * norm;
        const add = (i + r + 1) % size;
        const sub = (i - r + size) % size;
        acc += pass === 0 ? from[line * size + add] - from[line * size + sub] : from[add * size + line] - from[sub * size + line];
      }
    }
  }
}

/** Generate (or fetch cached) textures for a substrate kind at a texture size (power of two). */
export function substrateTextures(kind: Exclude<SubstrateKind, 'bare'>, size: number, anisotropy: number): SubstrateTextures {
  const key = `${kind}@${size}`;
  const hit = cache.get(key);
  if (hit) {
    hit.albedo.anisotropy = hit.normal.anisotropy = hit.orm.anisotropy = anisotropy;
    return hit;
  }
  const spec = SUBSTRATE_SPECS[kind];
  const rng = new Rng(0x5eed + kind.length * 7919 + kind.charCodeAt(0) * 131);
  const N = size * size;
  const height = new Float32Array(N).fill(-1e3);
  const col = new Float32Array(N * 3);
  const rough = new Float32Array(N);
  const mmPerPx = (spec.tile * 1000) / size;

  for (let i = 0; i < N; i++) {
    col[i * 3] = spec.voidColor[0];
    col[i * 3 + 1] = spec.voidColor[1];
    col[i * 3 + 2] = spec.voidColor[2];
    rough[i] = 0.85;
  }

  let layerBase = 0;
  for (const layer of spec.layers) {
    const totalW = layer.palette.reduce((a, s) => a + s.w, 0);
    const rMeanPx = (0.5 * (layer.rMin + layer.rMax)) / mmPerPx;
    const aspMean = 0.5 * (layer.aspect[0] + layer.aspect[1]);
    const grainArea = Math.PI * rMeanPx * rMeanPx * aspMean;
    const count = Math.min(250_000, Math.round((layer.coverage * N) / Math.max(1, grainArea)));
    for (let g = 0; g < count; g++) {
      // Size distribution skewed toward small grains (sorted sediment).
      const u = rng.next();
      const rMm = layer.rMin + (layer.rMax - layer.rMin) * u * u * (3 - 2 * u) * (0.6 + 0.4 * u);
      const r = Math.max(0.6, rMm / mmPerPx);
      const asp = layer.aspect[0] + (layer.aspect[1] - layer.aspect[0]) * rng.next();
      const rx = r * Math.sqrt(asp), ry = r / Math.sqrt(asp);
      const rot = rng.next() * Math.PI;
      const cr = Math.cos(rot), sr = Math.sin(rot);
      const cx = rng.next() * size, cy = rng.next() * size;
      // Pick a swatch.
      let pick = rng.next() * totalW;
      let sw = layer.palette[0];
      for (const s of layer.palette) {
        pick -= s.w;
        if (pick <= 0) { sw = s; break; }
      }
      const j = 1 + (rng.next() - 0.5) * 2 * layer.jitter;
      const hueJ = (rng.next() - 0.5) * layer.jitter * 0.5;
      const gr = Math.min(1, sw.c[0] * j * (1 + hueJ)), gg = Math.min(1, sw.c[1] * j), gb = Math.min(1, sw.c[2] * j * (1 - hueJ));
      const gRough = Math.min(1, Math.max(0.05, (sw.rough ?? layer.roughness) + (rng.next() - 0.5) * 0.12));
      // Outline harmonics (irregular grains / fractured fragments).
      const a2 = layer.rough * (rng.next() - 0.5), p2 = rng.next() * 6.283;
      const a3 = layer.rough * (rng.next() - 0.5) * 0.8, p3 = rng.next() * 6.283;
      const a5 = layer.rough * (rng.next() - 0.5) * 0.6, p5 = rng.next() * 6.283;
      const sink = layerBase + (rng.next() * 0.5 - 0.35) * r;
      const hScale = layer.height * r;
      // Shell flakes get growth bands.
      const bandF = layer.profile === 'flake' ? 0.9 + rng.next() * 1.2 : 0;
      const ext = Math.ceil(Math.max(rx, ry) * (1 + Math.abs(a2) + Math.abs(a3) + Math.abs(a5)) + 1);
      const x0 = Math.floor(cx - ext), x1 = Math.ceil(cx + ext);
      const y0 = Math.floor(cy - ext), y1 = Math.ceil(cy + ext);
      for (let py = y0; py <= y1; py++) {
        const wy = ((py % size) + size) % size;
        const dy = py + 0.5 - cy;
        for (let px = x0; px <= x1; px++) {
          const dx = px + 0.5 - cx;
          // Into the grain's frame.
          const lx = (dx * cr + dy * sr) / rx;
          const ly = (-dx * sr + dy * cr) / ry;
          const d2 = lx * lx + ly * ly;
          if (d2 > 2.2) continue;
          const ang = Math.atan2(ly, lx);
          const edge = 1 + a2 * Math.cos(2 * ang + p2) + a3 * Math.cos(3 * ang + p3) + a5 * Math.cos(5 * ang + p5);
          const d = Math.sqrt(d2) / edge;
          if (d >= 1) continue;
          let prof: number;
          if (layer.profile === 'dome') prof = Math.sqrt(1 - d * d);
          else if (layer.profile === 'facet') prof = Math.min(1, (1 - d) * 1.8) * (0.85 + 0.15 * Math.cos(ang * 3 + p3));
          else prof = Math.min(1, (1 - d) * 4);
          const h = sink + hScale * prof;
          const wx = ((px % size) + size) % size;
          const idx = wy * size + wx;
          if (h <= height[idx]) continue;
          height[idx] = h;
          // Shading baked into albedo: slightly lighter crowns, darker rims, speckle.
          const spk = 1 + (rng.next() - 0.5) * 2 * layer.speckle;
          let shade = (0.84 + 0.16 * prof) * spk * (d > 0.82 ? 1 - (d - 0.82) * 0.9 : 1);
          if (bandF > 0) shade *= 0.93 + 0.07 * Math.sin(lx * 9 * bandF + ly * 2);
          col[idx * 3] = gr * shade;
          col[idx * 3 + 1] = gg * shade;
          col[idx * 3 + 2] = gb * shade;
          rough[idx] = gRough;
        }
      }
    }
    layerBase += 0.15 * (0.5 * (layer.rMin + layer.rMax)) / mmPerPx;
  }

  // Fill any never-touched pixel with the floor of the layer.
  let hMin = Infinity, hMax = -Infinity;
  for (let i = 0; i < N; i++) if (height[i] > -1e2) { hMin = Math.min(hMin, height[i]); hMax = Math.max(hMax, height[i]); }
  for (let i = 0; i < N; i++) if (height[i] <= -1e2) height[i] = hMin;

  // Mid-scale undulation (periodic value noise, 4 and 8 cells per tile).
  const und = spec.undulation * size;
  const lattice = (cells: number, seed: number) => {
    const v = new Float32Array(cells * cells);
    const r2 = new Rng(seed);
    for (let i = 0; i < v.length; i++) v[i] = r2.next();
    return v;
  };
  const l4 = lattice(4, 11), l8 = lattice(8, 23);
  const sample = (lat: Float32Array, cells: number, x: number, y: number) => {
    const fx = (x / size) * cells, fy = (y / size) * cells;
    const ix = Math.floor(fx), iy = Math.floor(fy);
    const tx = fx - ix, ty = fy - iy;
    const sx = tx * tx * (3 - 2 * tx), sy = ty * ty * (3 - 2 * ty);
    const g = (a: number, b: number) => lat[((b % cells) + cells) % cells * cells + (((a % cells) + cells) % cells)];
    return (g(ix, iy) * (1 - sx) + g(ix + 1, iy) * sx) * (1 - sy) + (g(ix, iy + 1) * (1 - sx) + g(ix + 1, iy + 1) * sx) * sy;
  };
  if (und > 0) {
    for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
      height[y * size + x] += und * (sample(l4, 4, x, y) * 0.65 + sample(l8, 8, x, y) * 0.35 - 0.5);
    }
  }

  // Cavity occlusion: how far below the local mean surface each pixel sits.
  const blur = new Float32Array(height);
  const scratch = new Float32Array(N);
  const rLast = spec.layers[spec.layers.length - 1];
  const blurR = Math.max(2, (0.6 * (rLast.rMin + rLast.rMax)) / mmPerPx);
  boxBlurWrap(blur, size, blurR, scratch);
  boxBlurWrap(blur, size, blurR * 0.6, scratch);

  hMin = Infinity; hMax = -Infinity;
  for (let i = 0; i < N; i++) { hMin = Math.min(hMin, height[i]); hMax = Math.max(hMax, height[i]); }
  const hRange = Math.max(1e-6, hMax - hMin);

  const albedo = new Uint8Array(N * 4);
  const normal = new Uint8Array(N * 4);
  const orm = new Uint8Array(N * 4);
  const meanLin = [0, 0, 0];
  const cavK = 1.4 / Math.max(1, blurR);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const cav = Math.max(0, blur[i] - height[i]);
      const ao = Math.max(0.25, Math.min(1, 1 - cav * cavK));
      // Crevices are also shadowed from the direct light, which a normal map cannot do: bake
      // part of the occlusion into albedo.
      const dark = 0.45 + 0.55 * ao;
      const r = col[i * 3] * dark, g = col[i * 3 + 1] * dark, b = col[i * 3 + 2] * dark;
      albedo[i * 4] = Math.round(Math.min(1, r) * 255);
      albedo[i * 4 + 1] = Math.round(Math.min(1, g) * 255);
      albedo[i * 4 + 2] = Math.round(Math.min(1, b) * 255);
      albedo[i * 4 + 3] = Math.round(((height[i] - hMin) / hRange) * 255);
      meanLin[0] += srgbToLinear(Math.min(1, r));
      meanLin[1] += srgbToLinear(Math.min(1, g));
      meanLin[2] += srgbToLinear(Math.min(1, b));
      // Normal from central differences (height in px units → true slopes).
      const xl = (x - 1 + size) % size, xr = (x + 1) % size, yu = (y - 1 + size) % size, yd = (y + 1) % size;
      const dhx = (height[y * size + xr] - height[y * size + xl]) * 0.5;
      const dhy = (height[yd * size + x] - height[yu * size + x]) * 0.5;
      let nx = -dhx, ny = -dhy, nz = 1;
      const inv = 1 / Math.hypot(nx, ny, nz);
      nx *= inv; ny *= inv; nz *= inv;
      normal[i * 4] = Math.round((nx * 0.5 + 0.5) * 255);
      // DataTexture rows are uploaded unflipped: memory row y grows with +v, so ny is already +v.
      normal[i * 4 + 1] = Math.round((ny * 0.5 + 0.5) * 255);
      normal[i * 4 + 2] = Math.round((nz * 0.5 + 0.5) * 255);
      normal[i * 4 + 3] = 255;
      orm[i * 4] = Math.round(ao * 255);
      orm[i * 4 + 1] = Math.round(Math.min(1, rough[i] + (1 - ao) * 0.3) * 255);
      orm[i * 4 + 2] = 0;
      orm[i * 4 + 3] = 255;
    }
  }

  const mk = (data: Uint8Array, srgb: boolean) => {
    const t = new DataTexture(data, size, size, RGBAFormat, UnsignedByteType);
    t.wrapS = t.wrapT = RepeatWrapping;
    t.magFilter = LinearFilter;
    t.minFilter = LinearMipmapLinearFilter;
    t.generateMipmaps = true;
    t.anisotropy = anisotropy;
    if (srgb) t.colorSpace = SRGBColorSpace;
    t.needsUpdate = true;
    return t;
  };
  const result: SubstrateTextures = {
    albedo: mk(albedo, true),
    normal: mk(normal, false),
    orm: mk(orm, false),
    meanAlbedo: new Color(meanLin[0] / N, meanLin[1] / N, meanLin[2] / N),
    spec,
  };
  result.albedo.name = `substrate.${kind}.albedo`;
  cache.set(key, result);
  return result;
}
